### ISSUE TITLE
failed to look up field size from DDL CREATE TABLE sites

### ISSUE THREAD

**Issue by shipengfish** [acheong08/rev-obsidian-sync#14]
version: 0.1.0

![image](https://github.com/acheong08/rev-obsidian-sync/assets/7721612/856f4d31-0c59-4c79-8d26-f8de308978c3)

**Comment by acheong08** [comment]
Looks like a migration failure. Try `rm *.db` (make sure to back them up first if there's anything important in them already that isn't on a local device)

**Comment by shipengfish** [comment]
> Looks like a migration failure. Try `rm *.db` (make sure to back them up first if there's anything important in them already that isn't on a local device)

Thanks.
After rm *.db,it works.
