### ISSUE TITLE
How to sync .obsidian folder/custom files, etc...

### ISSUE THREAD

**Issue by truongmanhsang** [acheong08/rev-obsidian-sync#15]
I have installed the server, and it's working perfectly, but I see that it only syncs specific files, like .md, .png,... How to make it sync all the files/folder (like .obsidian folder)? By the way, thank you for your awesome work.

**Comment by ShiinaRinne** [comment]
![image](https://github.com/acheong08/rev-obsidian-sync/assets/45081750/2c6cbf98-ba09-4e8b-94e5-49de919e0adc)

![image](https://github.com/acheong08/rev-obsidian-sync/assets/45081750/1400be46-4ff6-48f5-9fa8-06b19aabd6bc)

**Comment by truongmanhsang** [comment]
@ShiinaRinne 
Thank you so much, I didn't even know this menu existed.
