### ISSUE TITLE
How to use publish

### ISSUE THREAD

**Issue by StudyingLover** [acheong08/rev-obsidian-sync#17]
I wonder how to use publish by this repo

**Comment by acheong08** [comment]
Enable the publish plugin from the core plugins and use it normally. Without the nginx configuration, documents show up at `https://yourdomain.com/published/<site>/<document>.md`

Will document when it's more well tested & add support for rendering the markdown

**Comment by StudyingLover** [comment]
I meet a mistake which is Network unavailable, but sync is available
![image](https://github.com/acheong08/rev-obsidian-sync/assets/68844494/cdbe3ab9-ad7c-4542-80c8-5ab22275a40e)

**Comment by acheong08** [comment]
`ctrl+i` and see what the error message is

**Comment by acheong08** [comment]
It's also possible that you're on an outdated version of the server that has yet to add publish support (It was added in https://github.com/acheong08/rev-obsidian-sync/releases/tag/v0.0.3 )

You might also need to update the plugin to https://github.com/acheong08/rev-obsidian-sync-plugin/releases/tag/1.0.5

**Comment by acheong08** [comment]
Edit: There seems to have been a regression in the latest release. I'm fixing it

**Comment by StudyingLover** [comment]
![image](https://github.com/acheong08/obi-sync/assets/68844494/5e1fa23e-52ae-4672-8d20-ce06626032a2)
I have been used newest version. but the problem still exist. But today I found the plugin doesn't work.I find the inference has benn been https://api.obsidian.md/user/signin , what should I do

**Comment by acheong08** [comment]
https://github.com/acheong08/obi-sync/issues/19

You need to downgrade Obsidian

**Comment by StudyingLover** [comment]
That's really a bad news :sob: ,I will consider it seriously.Thanks for your reply and repo
