### ISSUE TITLE
multi-arch support for docker image

### ISSUE THREAD

**Issue by winneratwin** [acheong08/rev-obsidian-sync#18]
i was interested in this project and wanted to host it on my raspberry pi but got an error when using docker-compose.

```
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

checked it out and the docker images are only built for amd64 at the moment meaning nobody with arm CPUs will be able to use the server.

**Comment by acheong08** [comment]
Not sure if this fixes it: https://github.com/acheong08/rev-obsidian-sync/commit/fa2c4f91a38d6f4eec1aa918ed9a9c3d7562e451

**Comment by acheong08** [comment]
https://github.com/acheong08/rev-obsidian-sync/pkgs/container/rev-obsidian-sync/123977025?tag=latest

>  linux/arm64

**Comment by wangweitung** [comment]
It seems amd64 not supported in the latest publish ?
@acheong08
