### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by HexyeDEV** [acheong08/rev-obsidian-sync#2]
Getting fork/exec /tmp/go-build988693008/b001/exe/main: permission denied Wwhen running main.go

**Comment by acheong08** [comment]
Looks like a problem with your Go installation? There is nothing that requires root

**Comment by acheong08** [comment]
https://stackoverflow.com/questions/14943917/go-fork-exec-permission-denied-error

You don't have write or execute permission to /tmp
