### ISSUE TITLE
Docker compose issue

### ISSUE THREAD

**Issue by yorurr** [acheong08/rev-obsidian-sync#20]
Hi there,

First congrats on the progress so far, this project looks promising! I tried to run the sync server with docker-compose file provided in the Wiki but to no avail.

Environment info:
Two VM's running Debian 11 x64, Docker 24.0.5, using the docker compose config as-is.

Issue encountered:
The sync server was started with docker compose up, and was listing on 127.0.0.1:3000, which was exposed as port 3000 on the host. I tried access the server using both IP:3000 and nginx reverse proxy: the IP:3000 returns "curl: (56) Recv failure: Connection reset by peer" no matter accessing from localhost or Internet, and the nginx proxy shows 502 bad gateway, which means it's not talking to the upstream.

I've checked the provided docker-compose file, it's pretty straight-forward, and it looks just fine, no idea why it's not working as intended.

**Comment by johe123qwe** [comment]
I have the same problem

**Comment by acheong08** [comment]
> The sync server was started with docker compose up, and was listing on 127.0.0.1:3000

Listen on 0.0.0.0:3000 inside docker. localhost might not be exposed correctly

**Comment by yfffy** [comment]
> > The sync server was started with docker compose up, and was listing on 127.0.0.1:3000
> 
> Listen on 0.0.0.0:3000 inside docker. localhost might not be exposed correctly

This may be the cause, the docker-compose file's ENV entries specified ADDR_HTTP=0.0.0.0:3000, but inside the container it listend on 127.0.0.1

![image](https://github.com/acheong08/rev-obsidian-sync/assets/94418067/67bbd4ea-6514-4b92-b15c-02a079bf363c)
