### ISSUE TITLE
Maintain compatibility with newer versions of Obsidian sync? - yes

### ISSUE THREAD

**Issue by obvionaoe** [acheong08/rev-obsidian-sync#22]
Hi, I was going to start using this server but just saw that you stopped using Obsidian.

Does this mean that this server will no longer support newer versions of Obsidian?
Or will you still maintain compatibility even though you aren't using it anymore?

Thanks for your work

**Comment by acheong08** [comment]
>  Or will you still maintain compatibility even though you aren't using it anymore?

Yes.

**Comment by obvionaoe** [comment]
Thanks so much!
