### ISSUE TITLE
Docker Install

### ISSUE THREAD

**Issue by Aetherinox** [acheong08/rev-obsidian-sync#23]
Maybe I'm losing my mind. Running on Ubuntu with docker.
Pulled using
```
docker pull ghcr.io/acheong08/obi-sync:latest
```

And received:

> no matching manifest for linux/amd64 in the manifest list entries

However if I use the following since I'm on Linux:
```
docker pull ghcr.io/acheong08/obi-sync:latest@sha256:97f08009a21f0c78f07c115df42df79e5acef3bf8beab40a70f4a3906fc10283
```

It will download properly, but when I issue:
```
docker compose up -d
```

I get:
> The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested 

Granted, I've only been using docker for a few months now, but thus far I've installed 7 projects without issue, and this is the first one to throw headaches. Not sure what I'm missing.

I think it's the same issue referenced in https://github.com/acheong08/obi-sync/issues/18#issuecomment-1706553811

Thanks

**Comment by acheong08** [comment]
It seems I made a mistake with the matrix in GitHub actions. Working on it

**Comment by acheong08** [comment]
https://github.com/acheong08/obi-sync/releases/tag/v0.1.4 (Wait for GitHub actions to complete)

**Comment by acheong08** [comment]
> I think it's the same issue referenced in https://github.com/acheong08/obi-sync/issues/18#issuecomment-1706553811

I missed that. GitHub didn't notify me via email for some reason

**Comment by anmolw** [comment]
I had the same issue with v0.1.4. Changing the image in docker-compose.yml to `ghcr.io/acheong08/obi-sync:latest` worked.

**Comment by acheong08** [comment]
Thanks. I forgot to update docker after the rename
