### ISSUE TITLE
Publish Issues

### ISSUE THREAD

**Issue by Aetherinox** [acheong08/rev-obsidian-sync#25]
Hey, had to step away, this is part 2 of #24 

In short, the issue still exists that I cannot view the online published MD files using publish.domain.com (with your nginx template). The site itself works and I get json formatted error messages, but it can never find the pages / slug.

So I tried out a series of tests. 
When originally executing:
```curl
curl --request POST --url https://api.domain.com/publish/list --header 'Content-Type: application/json' --data '{ "token": "xxx"}'
```

It would return:
```json
{"limit":1,"shared":[],"sites":[]}
```

I tried numerous re-creations of the vault, wiped info, etc. Nothing ever worked.

I then manually entered:
```curl
curl --request POST --url https://api.domain.com/publish/create --header 'Content-Type: application/json' --data '{ "token": "xxx"}'
```

And it created a slug for me as `755625b4-86c5-43cd-84fa-89f2b415596c`

I used that slug as part of the domain url `https://publish.domain.com/SLUG_HERE` and I actually get information returned in json now

```json
{
  "error": "record not found",
  "path": "",
  "site": {
    "id": "3540989e-c7c6-5aac-ba5f-7e7127baac43",
    "host": "domain.com",
    "slug": "755625b4-86c5-43cd-84fa-89f2b415596c"
  }
}
```

Before I was just getting `Record Not Found` and nothing else.

I'm not sure if I'm onto something here, I'm just tracing all the code backward to figure out where the issue could be, in case any of this helps out. It seems like my vaults aren't getting a slug, so the webserver can't find the pages. I've tried numerous vaults now, and can access no .md pages.

**Edit**: Did a wipe and started fresh.
Linked obsidian account, enabled sync / public and then synced my starter vault. Which gives me the sites list of:
```json
{"limit":1,"shared":[],"sites":[]}
```

Decided to use this command to see if I could assign a slug to the newly created vault uid with:
```curl
curl --request POST --url https://obsidian.domain.com/api/slug --header 'Content-Type: application/json' --data '{ "id": "06d68834-b7e4-42e9-b72a-592d456ff3a3", "slug": "Test", "token": "xxxx"}'
```

Which returns
> {"error":"You do not have permission to change this site's slug"}

Attempted to access the online published site using the URLs:
```
https://publish.domain.com/Test/Welcome.md
https://publish/domain.com/06d68834-b7e4-42e9-b72a-592d456ff3a3/Welcome.md
```

`Test` being the name I made for the vault, and the 2nd one being the UID auto assigned to the vault to see if either one of the two would work.

Both URL attempts return
> {"error":"Site not found"}

On a positive note, after the endless hours of screwing around with this, I was able to edit the docker-compose file and get the vault database to save in a specified location. For some reason, the default docker-compose template doesn't have a period at the front of the path, but as soon as I added a period, it started saving in the folder where I originally specified it to go.

**Comment by acheong08** [comment]
> And it created a slug for me as 755625b4-86c5-43cd-84fa-89f2b415596c

Looks like you made a mistake by trying to work through it via curl. The publish plugin makes 2 requests to create a site, one to create and another to set the site (slug) name

**Comment by acheong08** [comment]
[Screencast from 2023-09-09 15-42-41.webm](https://github.com/acheong08/obi-sync/assets/36258159/c53ad4ff-7191-4b72-aacd-b263f68e6a18)

**Comment by acheong08** [comment]
The flow goes something like this:
1. Check if the site already exists:
```js
fetch("https://api.domain.com/api/site", {
  "body": "{\"slug\":\"generic\",\"token\":\"<token>\"}",
  "method": "POST"
});

{"code":"NOTFOUND","message":"Slug not found"}
```

2. Create a new site
```js
fetch("https://obsidian.duti.me/publish/create", {
  "body": "{\"token\":\"<token>\"}",
  "method": "POST"
});

{
    "id": "514e3e1a-f5d7-46d2-83d0-0c6fa7b5a584",
    "host": "api.domain.com",
    "created": 1694245459098,
    "owner": "<your email>",
    "slug": "a0ccf713-7b3c-4b82-918d-d3824c4b1e42",
    "size": 0
}
```

Ignore the slug.

4. Set the actual slug
```js
fetch("https://obsidian.duti.me/api/slug", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US",
    "content-type": "application/json; charset=utf-8",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Linux\"",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"id\":\"514e3e1a-f5d7-46d2-83d0-0c6fa7b5a584\",\"host\":\"api.domain.com\",\"slug\":\"<actual slug>\",\"token\":\"<token>\"}",
  "method": "POST"
});
```

**Comment by Aetherinox** [comment]
Just woke up a bit ago, so my brain isn't fully functioning yet.

Which interface are you on where it says "Manage Sites". Because I've been to the Sync section, and the one setting for the plugin itself, and I can't seem to find this.

The places I've been modifying settings from was Sync -> Remote Vault

![jOGm1v8](https://github.com/acheong08/obi-sync/assets/118329232/9a12ee5e-df91-4103-bf10-e4d9e82d592c)

I don't see an interface at all such as yours. Unless I'm missing a critical part.

And if I go to "Core Plugins" and locate "Publish", I see no settings button at all.

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/obi-sync/assets/36258159/e77f97e3-be24-4b05-98ac-1c02a69da0e4)

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/obi-sync/assets/36258159/3e6962f6-d601-4b09-8858-8fd145ea55f4)

**Comment by acheong08** [comment]
> I don't see an interface at all such as yours. Unless I'm missing a critical part.

I think now I understand the confusion.

**Comment by Aetherinox** [comment]
Yeah I've been ALL over this program today trying to see how a slug is created, and I completely skipped that part. I have that button, but mine throws a network issue.

![ajclRYa](https://github.com/acheong08/obi-sync/assets/118329232/dd2e86e6-d7a8-4b5a-b1e8-947d44bbcac5)

**Comment by acheong08** [comment]
> Yeah I've been ALL over this program today trying to see how a slug is created, and I completely skipped that part. I have that button, but mine throws a network issue.

Check the network log. Have you updated the plugin?

**Comment by Aetherinox** [comment]
I double checked the Sync log to ensure it pushed all my files, and it connected fine. Also made sure I'm signed in via Obsidian. Are you referring to a special network log feature in Obsidian, or developer window.

**Comment by acheong08** [comment]
>  developer window.

yes. ctrl+shift+i should open it

**Comment by acheong08** [comment]
The publish feature is completely separate from sync

**Comment by Aetherinox** [comment]
Yeah, starting to see that. Should have seen it this morning, but I was digging into something much more complicated. Part of the issue is I have too many plugins including the left bar, so I would have never noticed a new icon.

In regards to network, the only entry I'm seeing is:

![OUFueoaPz5](https://github.com/acheong08/obi-sync/assets/118329232/1117f445-7041-4e6a-acfc-4f728b36567e)

The URL seems to be different. It's looking for `https://domain.com/api/list` whereas, my subdomain is `obsidian.domain.com`, does the URL have to be API as the subdomain?

**Comment by acheong08** [comment]
> The URL seems to be different. It's looking for https://domain.com/api/list whereas, my subdomain is obsidian.domain.com, does the URL have to be API as the subdomain?

No. Did you perhaps set the `DOMAIN_NAME` environment variable to something other than your subdomain?

**Comment by acheong08** [comment]
> obsidian.domain.com

That is how my domain name looks as well

![image](https://github.com/acheong08/obi-sync/assets/36258159/18094645-9d50-46fd-a3b5-5416b63c956c)

**Comment by Aetherinox** [comment]
Originally I had:
```
DOMAIN_NAME=domain.com
```

I now changed it to
```
DOMAIN_NAME=obsidian.domain.com
```

Restarted docker container, and it's still showing the original request url of `domain.com/api/list`, unless I'm missing something really damn simple here.

And `obsidian.domain.com` is a valid subdomain, working properly from browser.

**Comment by acheong08** [comment]
> Restarted docker container, and it's still showing the original request url of domain.com/api/list, unless I'm missing something really damn simple here.

The domain name is stored in the database. This was to allow horizontal scaling (incomplete). You need to delete `publish.db` and restart the container

**Comment by Aetherinox** [comment]
Done, gave obsidian a reboot just in case

Now it's showing `slugs` as one successful and one fail

![AjEOVEbn5j](https://github.com/acheong08/obi-sync/assets/118329232/c01af629-37ce-4364-b530-e393a23fbdd4)
![rZsomWlAgm](https://github.com/acheong08/obi-sync/assets/118329232/37688550-ae87-4b75-87e1-c3024fe0fef6)

Same domain as before with `publish.db` wiped and docker container restarted

**Comment by acheong08** [comment]
I'm not quite sure why it would still use the old domain name. Try clearing all the databases & deleting `/path/to/your/vault/.obsidian/publish.json`

**Comment by Aetherinox** [comment]
Yeah, doing all that now. Even wiping the docker container just to make sure something isn't caught.

**Comment by Aetherinox** [comment]
I swear this is so bizarre. Sync has always worked, but this time around after creating a new user, the log has:
```
2023-09-09 01:32 - Connecting to server
2023-09-09 01:32 - Did not respond to login request: {"error":"record not found"}

2023-09-09 01:32 - Connecting to server
2023-09-09 01:32 - Did not respond to login request: {"error":"record not found"}

2023-09-09 01:32 - Connecting to server
2023-09-09 01:32 - Did not respond to login request: {"error":"record not found"}

2023-09-09 01:33 - Connecting to server
2023-09-09 01:33 - Did not respond to login request: {"error":"record not found"}

2023-09-09 01:33 - Waiting to connect to server
```

Only change made was changing the env from `domain.com` to `obsidian.domain.com`

But now, Publish works, and I can create.

**Comment by acheong08** [comment]
> I swear this is so bizarre. Sync has always worked, but this time around after creating a new user, the log has:

Deleting the databases means you need to sign up & log in again.

> But now, Publish works, and I can create.

The reason publish works but sync doesn't is because the server uses JWT for tokens, meaning that a deleted user can still use certain functions for some time until the token expires. Might need to change that

**Comment by Aetherinox** [comment]
> > I swear this is so bizarre. Sync has always worked, but this time around after creating a new user, the log has:
> 
> Deleting the databases means you need to sign up & log in again

Yeah, did all that right after the container was restarted. I feel like I could start this damn thing blind-folded now. I don't know why, but Obsidian wanted me to disconnect from the sync and re-connect, and it started pushing after that. That didn't happen before.

On the shocking side of things, publish works, it uploaded my MD files

![P9V9zTN](https://github.com/acheong08/obi-sync/assets/118329232/249f323d-ef0b-4c27-9306-5e18bf7f5e1b)

```
2023-09-09 01:37 - Uploading Windows/PowerShell/BurntToast
2023-09-09 01:37 - Uploading Windows/Environment Variables
```

And I can now actually view the .md file code.
Aside from the fact that I feel like I can't even breathe on it and pray to the tech gods that nothing dies. It appears to be working.

Sorry this went in a direction so far outside the realm of normal. Not seeing that publish button royally screwed me up. I could have probably diagnosed it had I seen that. Because once I would have gotten fed up enough of it not connecting, I would have wiped again anyway. I've done it about 10 times today.

I feel like I need to create a damn Obsidian note on this plugin alone just of all the DOs and DONTs so if I need to re-configure it, I can remember everything.

Unfortunately, I do C#, PHP, Lua, and JS. I've messed with Go for about 5 minutes of my life, and I still don't have a full grasp of how Obsidian and plugins communicate together. Nor do I have the head room right now to learn it.

All I do know is this plugin is gold. I like to self-host everything. I get that Obsidian is secure by their standards, but I feel much more comfortable with my data being on my machine with me in control of security. Out of 80 plugins my vault has, this is easily one of my top 3.

Appreciate the hand holding, and sorry again this went WAY off the rails.

**Comment by acheong08** [comment]
Nice that it went well. Sorry about the trouble it gave you. I'm horrendous at documentation (hopefully will improve)

**Comment by Aetherinox** [comment]
> Nice that it went well. Sorry about the trouble it gave you. I'm horrendous at documentation (hopefully will improve)

No worries. I'm going to write up my own doc on it just so I've got troubleshooting once I get a firm understanding of how it functions. I'm going to at least write down the flow of commands you provided above so I know the basics of how it does its thing.

Appreciate the help again.

**Comment by acheong08** [comment]
> No worries. I'm going to write up my own doc on it just so I've got troubleshooting once I get a firm understanding of how it functions. I'm going to at least write down the flow of commands you provided above so I know the basics of how it does its thing.

Could you perhaps share your docs when you complete them? As someone who has no idea what docs are supposed to look like, it would be a great reference for improving the readme/wiki. Might also help out anyone that faces the same issue. Thanks

**Comment by Aetherinox** [comment]
> Could you perhaps share your docs when you complete them? As someone who has no idea what docs are supposed to look like, it would be a great reference for improving the readme/wiki. Might also help out anyone that faces the same issue. Thanks

Sure thing. I'll send you the link once I get them written up. Being in development over 15 years (and as you've seen in the last 24 hours with me), sometimes what may be painfully obvious to the developer, ends up being just a pain for the user. I've had to create docs that pretty much hold the person's hand because the better the docs, the less you get annoyed by tickets and the more time you get to work on a product. 

I'll just drop them in a repo with a readme and link you when I'm done. Got to create screenshots and all that jazz.

**Comment by Aetherinox** [comment]
@acheong08 Definitely not done, but I put the overall template together and I need to change some things from my configuration to the default and add sections for configuring the plugin, etc, but this is the just of my doc: https://github.com/Aetherinox/obi-sync-docs

Might be good as a readme, but even more details within the repo's wiki would be awesome.
