### ISSUE TITLE
HTTPS required when server not on localhost

### ISSUE THREAD

**Issue by zer0yu** [acheong08/rev-obsidian-sync#3]
I set it up by referring to your readme. However it does not open the synchronization process properly. I don't know if I need to apply https certificate? The specific error message is as follows:

<img width="670" alt="image" src="https://github.com/acheong08/rev-obsidian-sync/assets/16551733/e8baa994-a1b5-4746-8eb0-6168116a3dd6">
<img width="1063" alt="image" src="https://github.com/acheong08/rev-obsidian-sync/assets/16551733/412e8edc-2f9c-4098-b48d-fff5d0a5f3bf">

**Comment by acheong08** [comment]
Check your $HOST environment variable

**Comment by acheong08** [comment]
I might change the environment variable being read due to conflicts with pre-existing variables

**Comment by acheong08** [comment]
Also open up `database.db` and check what host the vault has stored.

**Comment by acheong08** [comment]
> I don't know if I need to apply https certificate

The answer is most likely yes unless you're running it on localhost. They use https by default for the websocket

**Comment by wangweitung** [comment]
> I set it up by referring to your readme. However it does not open the synchronization process properly. I don't know if I need to apply https certificate? The specific error message is as follows:
> 
> <img alt="image" width="670" src="https://user-images.githubusercontent.com/16551733/263525704-e8baa994-a1b5-4746-8eb0-6168116a3dd6.png"> <img alt="image" width="1063" src="https://user-images.githubusercontent.com/16551733/263525716-412e8edc-2f9c-4098-b48d-fff5d0a5f3bf.png">

咋配置的。。。能不能分享下教程。。。

**Comment by zer0yu** [comment]
Ok, I'll configure the https. I have two more questions:
1. Can I use IP directly for $HOST environment variable? 
2. Can you share the full Nignix config file?

**Comment by zxt-tzx** [comment]
Trying to get this to work locally:
- currently on a Mac (running both Obsidian + `go run cmd/obsidian-sync/main.go`)
- I used `export HOST=127.0.0.1`
- I updated the `Obsidian Sync URL` in the plugin to `http://localhost:3000`

The handlers are running and I can interact with them via cURL HTTP requests, but my Obsidian app on macOS doesn't seem to be working.

Happy to help with submitting PRs to get this working and developing this further (have been very annoyed by iCloud syncing not working well with Obsidian).

**Comment by ShiinaRinne** [comment]
I am getting this error when testing on my server (CentOS 7, nginx+ssl)

There is no data in the `database->file`
![image](https://github.com/acheong08/rev-obsidian-sync/assets/45081750/5886d5de-dcf9-4491-9ee5-3162adc98d74)

![image](https://github.com/acheong08/rev-obsidian-sync/assets/45081750/7187759e-f2df-45cf-8430-d3181e1d4b05)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/45081750/7db1bc98-08b1-45aa-9028-539e3d8ae683)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/45081750/313c07f3-280b-4d2e-b6d1-68fbc5ed32a1)

**Comment by acheong08** [comment]
> Trying to get this to work locally:
> 
>     * currently on a Mac (running both Obsidian + `go run cmd/obsidian-sync/main.go`)
> 
>     * I used `export HOST=127.0.0.1`
> 
>     * I updated the `Obsidian Sync URL` in the plugin to `http://localhost:3000`
> 
> 
> The handlers are running and I can interact with them via cURL HTTP requests, but my Obsidian app on macOS doesn't seem to be working.
> 
> Happy to help with submitting PRs to get this working and developing this further (have been very annoyed by iCloud syncing not working well with Obsidian).

When running on localhost, there is no need to export HOST.

**Comment by acheong08** [comment]
> but my Obsidian app on macOS doesn't seem to be working.

Did you install the plugin and configure the endpoint?

**Comment by acheong08** [comment]
To debug, you can open up the electron developer tools and do `location.reload()` to make sure all requests show up

**Comment by acheong08** [comment]
> Can I use IP directly for $HOST environment variable?

Yes.

**Comment by acheong08** [comment]
By default, if you don't configure it:
```go
var Host = "localhost:3000/ws"
```

**Comment by acheong08** [comment]
> Can you share the full Nignix config file?

That is the full nginx config. My SSL/TLS is being handled by Cloudflare

**Comment by acheong08** [comment]
If you're running on localhost, there is no need for nginx ofc

**Comment by acheong08** [comment]
Another possible issue:

There has been a lot of breaking changes over the past few days & hours as I add new features. You might need to delete the db files and restart (and sign up again) if you've pulled new versions

**Comment by wangweitung** [comment]
It seems I suffer the same issue
below is my configuration and could you help me，thanks!
I  have ubuntu server and a windows pc running obsidian.


1、 `git clone https://github.com/acheong08/obsidian-sync`  
2、`cd obsidian-sync`  
3、export HOST=192.168.1.204     - this is my ubuntu server ip  
4、go run cmd/obsidian-sync/main.go  
5、copy the code to nigx cofig file   
![image](https://github.com/acheong08/rev-obsidian-sync/assets/8080125/1e73841f-4870-4160-8e8b-f3dc18681add)

6.set the plugin sync URL
![image](https://github.com/acheong08/rev-obsidian-sync/assets/8080125/88a406d8-8db1-44d0-be6c-49b4602ca41c)
7.create user and login
![image](https://github.com/acheong08/rev-obsidian-sync/assets/8080125/13b3fa49-2010-4531-9a79-d43f412c8d80)

8. I still get the error code 1006
![image](https://github.com/acheong08/rev-obsidian-sync/assets/8080125/0b77da7a-1106-468d-847f-4d4e8405d419)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/8080125/4796e6a8-2590-4e78-8817-86524263bfad)

9. where did I do wrong ?please help

**Comment by acheong08** [comment]
I don't see any connections to /ws or /.
Check where it's connecting via developer tools for the websocket

**Comment by acheong08** [comment]
Hmm. All the requests are OPTIONS. Looks like CORS is failing somehow

**Comment by acheong08** [comment]
Edit: Sorry. Light mode is killing me.

**Comment by wangweitung** [comment]
> Edit: Sorry. Light mode is killing me.

sorry....  I did not use dark mode...

**Comment by acheong08** [comment]
> ![image](https://user-images.githubusercontent.com/8080125/263539578-0b77da7a-1106-468d-847f-4d4e8405d419.png)

What app is this?

**Comment by wangweitung** [comment]
> > ![image](https://user-images.githubusercontent.com/8080125/263539578-0b77da7a-1106-468d-847f-4d4e8405d419.png)
> 
> What app is this?

opened from here

![image](https://github.com/acheong08/rev-obsidian-sync/assets/8080125/fb034d28-0aa3-4661-a269-6bac1f77d3b4)

**Comment by acheong08** [comment]
`Ctrl + Shift + I` to open devtools. It'll show what's going wrong. Then in console `location.reload()`

**Comment by wangweitung** [comment]
> location.reload()

sorry for the light mode ...

![image](https://github.com/acheong08/rev-obsidian-sync/assets/8080125/cd39b564-3e5c-48a4-9e46-9d1dc4eb9b61)

**Comment by acheong08** [comment]
Ah here it is. It's using wss:// instead of ws://. It expects HTTPS when the endpoint is anything other than localhost or 127.0.0.1

**Comment by wangweitung** [comment]
> Ah here it is. It's using wss:// instead of ws://. It expects HTTPS when the endpoint is anything other than localhost or 127.0.0.1

what should I do to make it work?

**Comment by acheong08** [comment]
> what should I do to make it work?

Use something like certbot to get an TLS certificate.

**Comment by wangweitung** [comment]
> > what should I do to make it work?
> 
> Use something like certbot to get an TLS certificate.

I just use it in my inner network at home... could TLS be skipped？

**Comment by acheong08** [comment]
Here is the bit of code in the Obsidian app that manages this:
```js
(t.prototype.getHost = function () {
              var e = this.host || "127.0.0.1:3003";
              return e.startsWith("127.0.0.1") || e.startsWith("localhost")
                ? "ws://" + e
                : "wss://" + e;
            }),
```

Another solution is to update the plugin to also intercept wss/ws requests but that'll take a while. (I have 0 experience in JS)

**Comment by acheong08** [comment]
> could TLS be skipped？

It's hard coded into the app. For now, no

**Comment by wangweitung** [comment]
> > what should I do to make it work?
> 
> Use something like certbot to get an TLS certificate.

https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal&tab=standard

I'm trying by this instruction now...

**Comment by acheong08** [comment]
```js
if (this.settings.SyncAPI.startsWith("http://")) {
	// Websocket intercept
	const originalWebSocket = window.WebSocket;

	// Override the WebSocket constructor
	window.WebSocket = class CustomWebSocket extends originalWebSocket {
		constructor(url: string, protocols?: string | string[]) {
			const newUrl = url.replace("wss://", "ws://");
			super(newUrl, protocols);
		}
	};
}
```
This might work in the plugin. Testing

**Comment by acheong08** [comment]
Issue: app.js loads before plugins. They make it a constant

**Comment by wangweitung** [comment]
> Issue: app.js loads before plugins. They make it a constant

still thanks for ur effort...

**Comment by acheong08** [comment]
Note to whomever comes across this issue again: Cannot fix. HTTPS is required when not localhost

**Comment by tan-zx** [comment]
> `Ctrl + Shift + I` to open devtools. It'll show what's going wrong. Then in console `location.reload()`

Thank you so much for this. What I've done:
- include `console.log` statements in the plugin to see when the plugin is loaded and unloaded
- created an account and signed in on the About tab (this seems to be successful)

I see requests being made to the `https://api.obsidian.md/user/info` endpoints which are successfully intercepted by my local server, but I do not see any syncing attempts via the websocket connection.

<img width="527" alt="image" src="https://github.com/acheong08/rev-obsidian-sync/assets/67887489/15055d05-7934-4e0c-b2d2-3b63ac212f99">

![image](https://github.com/acheong08/rev-obsidian-sync/assets/67887489/23092c4b-b8e9-4cdf-b2bf-1c7bca84ba53)

Do I need to manually turn on Obsidian Sync from somewhere within the application's preference settings?

Sorry if this is not the right thread, I could create a [new issue here](https://github.com/acheong08/rev-obsidian-sync-plugin/issues/new) instead.

**Comment by zxt-tzx** [comment]
> `Ctrl + Shift + I` to open devtools. It'll show what's going wrong. Then in console `location.reload()`

Thank you so much for this. What I've done:
- include `console.log` statements in the plugin to see when the plugin is loaded and unloaded
- created an account and signed in on the About tab (this seems to be successful)

I see requests being made to the `https://api.obsidian.md/user/info` endpoints which are successfully intercepted by my local server, but I do not see any syncing attempts via the websocket connection.

Do I need to manually turn on Obsidian Sync from somewhere within the application's preference settings?

UPDATE: ah ok my bad, I need to turn on Sync within the Core Plugins page. will tinker further.

UPDATE 2: It's working now! What I did
- Move my existing Vault out of iCloud
- Go to Core plugins > Sync and connect to a new remote vault

~~Sorry if this is not the right thread, I could create a [new issue here](https://github.com/acheong08/rev-obsidian-sync-plugin/issues/new) instead.~~

Thanks again!

**Comment by CzBiX** [comment]
it's possible to use HTTP. you just have to hack the `getHost` of sync plugin.
solution [here](https://github.com/CzBiX/ob-sync-server/commit/2d585fb95f8805082448fefd5489749927541b92).

**Comment by acheong08** [comment]
@CzBiX Thank you! I don't actually know JavaScript, could you explain how you found this?
> `this.getInternalPluginInstance('sync').getHost = ()`

I thought of the same but was unable to implement it because I couldn't find where the getHost function was

**Comment by acheong08** [comment]
I'm getting `Property 'internalPlugins' does not exist on type 'App'.ts(2339)`

**Comment by CzBiX** [comment]
@acheong08  It's not easy to explain, but in short, this is all that you can get with reverse engineering.

>I'm getting Property 'internalPlugins' does not exist on type 'App'.ts(2339)

This is a non-public API that is not exposed, you have to use `any` in ts.

**Comment by acheong08** [comment]
`// @ts-ignore: Property 'internalPlugins' does not exist on type 'App'.`

This worked. Thank you!

**Comment by acheong08** [comment]
CC @wangweitung 

You can update from https://github.com/acheong08/rev-obsidian-sync-plugin/releases/tag/1.0.3

Perhaps for the plugin, we can switch to using @CzBiX's repository considering they're much more experienced with JS

**Comment by wangweitung** [comment]
> CC @wangweitung
> 
> You can update from https://github.com/acheong08/rev-obsidian-sync-plugin/releases/tag/1.0.3
> 
> Perhaps for the plugin, we can switch to using @CzBiX's repository considering they're much more experienced with JS

thank you both , it's happy to hear this good news!
