### ISSUE TITLE
The Server is not working in windows

### ISSUE THREAD

**Issue by UveshRajwani** [acheong08/rev-obsidian-sync#7]
So i am trying to run the server in windows i am able to create a user but not able to login. I am getting the error sql: no rows in result set
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/8cbb8da3-0e65-4bdd-bf23-dfb3c23b71a7)

**Comment by acheong08** [comment]
```bash
acheong@toolbox ~/P/obsidian-sync (main)> go run cmd/signup/main.go
Enter your full name: Example User 1
Enter email: example1@example.com
Enter password: ⏎                                                               
acheong@toolbox ~/P/obsidian-sync (main)> curl http://127.0.0.1:3000/user/signin -X POST -d '{"email":"example1@example.com","password":"example1"}'
{"error":"Login failed, please double check your email and password."}⏎         
acheong@toolbox ~/P/obsidian-sync (main)> curl http://127.0.0.1:3000/user/signin -X POST -d '{"email":"example1@example.com","password":"example"}'
{"email":"example1@example.com","license":"","name":"Example User 1","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxQGV4YW1wbGUuY29tIn0.o02cjuzcTcBg8xxgyxGzApyvFk3T7EzrX0P_doY287c"}
```

Failed to reproduce on a fresh instance (Linux)

Is it Windows specific?

**Comment by UveshRajwani** [comment]
hey @acheong08 I just checked on on a fresh instance it works it could be Windows specific

**Comment by UveshRajwani** [comment]
in windows it is able to write to the db but not able to read form db (just did it all on my laptop same problem)

**Comment by acheong08** [comment]
The main branch has been updated to use [go-gorm/gorm](https://github.com/go-gorm/gorm) with a different sqlite driver. See if that helps

**Comment by UveshRajwani** [comment]
Yes now it works but there is a new problem. when i make a new user from the the cmd (cmd/signup/main.go) the user is not created but when i use the api to make the same user it works
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/e76bd7db-73ee-4933-aad1-5dc11ffc8716)

**Comment by acheong08** [comment]
https://github.com/acheong08/rev-obsidian-sync/blob/0cb8f7f55a286ebd4a6c1325245b86dee4d305b0/cmd/signup/main.go#L37

https://github.com/acheong08/rev-obsidian-sync/blob/0cb8f7f55a286ebd4a6c1325245b86dee4d305b0/api/handlers/user.go#L104

It's running the same code

**Comment by UveshRajwani** [comment]
I could show you this problem over a call on discord or google meet if you want

**Comment by acheong08** [comment]
Could you perhaps add a few log/print statements to check whether values are being passed around correctly?

There is a possibility that it's something to do with the input. Also check the database to see if anything is being written

**Comment by UveshRajwani** [comment]
this is when i started the program (cmd/obsidian-sync/main.go)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/8df73fa0-c0df-46f8-ba49-52c266c90638)
now i added a user using the cmd  (cmd/signup/main.go)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/29f19323-a89b-4606-b12e-1cc4bf020968)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/c5732308-4b3d-4538-b494-290eae34879b)
now when i add the user using the api the user is the user is now working
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/5aa01505-d421-4f45-919c-8390e02d6c9a)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/8eb62596-990c-44a5-93b7-0d7eadd8a5c1)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/b8dbfba3-e86d-4c92-9879-76acc88ad09a)

**Comment by acheong08** [comment]
right. I mean add a few `log.Println(...)` around the signup command and open the database and see if anything is being inserted. There could be an extra space or something caused by whatever Windows uses for input

**Comment by UveshRajwani** [comment]
also one more this when i try to add the same user which i add using the api it give me a error. so it is able to read but not able to write
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/b286533a-9ffb-44cb-9f54-57f8a58034c4)

**Comment by UveshRajwani** [comment]
tried added a user with log 
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/1e31e84a-53d8-4762-8792-372ba5408565)
![image](https://github.com/acheong08/rev-obsidian-sync/assets/63191143/54cf6a27-b0e9-4fe5-b0e4-e5296a6ef844)
but the thing i am not understanding is both the cmd and the api use the name func (vault.NewUser) so why does only one work

**Comment by acheong08** [comment]
Tested in a Windows VM and it worked for me™. Since the API works already, I suppose just use that. It would be too much effort to find what specifically went wrong in your case.
